apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-user-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-user-service
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}