replicaCount: 1

image:
  repository: pixelopscloud/shopnow-frontend
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"